apiVersion: 1

datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    database: airflow
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: "disable"
      maxOpenConns: 100 
      maxIdleConns: 10  
      connMaxLifetime: 14400
