{
 "title": "Case Tecnico",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Informações - Clientes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Novos Contratos - Receita Anual (Milhões)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  ano AS \"Ano de Operação\",\n  (total_valor_contrato_anual / 1000000) AS \"Receita R$ (Milhões)\"\nFROM\n  insight_cliente_ano"
    }
   ]
  },
  {
   "title": "Novos Contratos - Anual",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  ano AS \"Ano de Operação\",\n  total_clientes AS \"Novos Clientes\"\nFROM\n  insight_cliente_ano"
    }
   ]
  },
  {
   "title": "Clientes Por Estado",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  estado AS \"Estado\",\n  total_clientes AS \"Total Clientes\"\nFROM\n  insight_geografico_clientes"
    }
   ]
  },
  {
   "title": "Setor Responsável por Clientes",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  nivel AS \"Nível\",\n  total_clientes AS \"Total Clientes\"\nFROM\n  insight_nivel_cliente"
    }
   ]
  },
  { "title": "Informações - Funcionários", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Média Salarial",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 1, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  nivel AS \"Nível\",\n  ROUND(CAST(media_salario_base as numeric), 2)  AS \"Media Salarial (R$)\"\nFROM\n  insight_salario_nivel\n"
    }
   ]
  },
  {
   "title": "Total Funcionários por Nível",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  nivel AS \"Nível\",\n  total_funcionarios AS \"Total Funcionários\"\nFROM\n  insight_funcionarios_nivel"
    }
   ]
  }
 ]
}